name: Development

on:
  push:
    branches:
      - development

jobs:
  lint:
    name: Lint
    type: custom
    steps:
      - uses: eas/checkout

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    name: Tests
    type: custom
    steps:
      - uses: eas/checkout

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --runInBand --passWithNoTests # Remove once tests are added

  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: development

  get_android_build:
    name: Check for existing Android build
    needs:
      - lint
      - test
      - fingerprint
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: development

  build_android:
    name: Build Android
    needs:
      - get_android_build
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: development

  publish_android_update:
    name: Publish Android update
    needs:
      - get_android_build
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    params:
      channel: development
      platform: android
